language: php
php:
    - 7.1
    - 7.0
    - 5.6
    - hhvm

dist: trusty
sudo: false

before_script:
    - composer install
    - mkdir -p build/logs

script:
  - vendor/bin/phpunit

after_script:
    - if [ "$TRAVIS_BRANCH" == "prod" ] && [ $TRAVIS_PHP_VERSION == "7.0" ]; then vendor/bin/coveralls; fi

notifications:
  email: false