language: php
php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

before_script:
  - composer install
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit

after_script:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ $TRAVIS_PHP_VERSION == "7.1" ]; then vendor/bin/coveralls; fi

notifications:
  email: false