language: php
php:
    - 7.0
    - 5.6
    - hhvm

dist: trusty
sudo: false

before_script:
    - composer install
    - mkdir -p build/logs

script:
  - vendor/bin/phpunit

after_script:
    - vendor/bin/coveralls

notifications:
  email: false